apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-squn
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr714-0075-0024-tenant/tkrw-pr714-0075-0024-app/devfile-sample-squn@sha256:bb887fa54f9dc0c28951575b0bd8cd32a35af8cd77ff452324d429cf43d4a46c
        name: my-nodejs
        resources: {}
status: {}
